[versions]
kotlin = "2.3.0"
logback = "1.5.37"
ktor = "3.6.0"
bcrypt = "0.10.2"
javaJwt = "4.4.0"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }